name       : librttopo
version    : 1.1.0
release    : 2
source     :
    - https://git.osgeo.org/gitea/rttopo/librttopo/archive/librttopo-1.1.0.tar.gz : 2e2fcabb48193a712a6c76ac9a9be2a53f82e32f91a2bc834d9f1b4fa9cd879f
homepage   : https://strk.kbt.io/projects/rttopo/
license    : GPL-2.0-or-later
component  : programming.library
summary    : RT Topology Library
description: |
    The RT Topology Library exposes an API to create and manage standard (ISO 13249 aka SQL/MM) topologies using user-provided data stores.
builddeps  :
    - pkgconfig(geos)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
